---

- hosts: all
  become: true
  tasks:

  - name: install apache and php in CentOS and Ubutun
    package:
      name:
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest
      update_cache: yes
   
