---

- hosts: all
  become: true
  tasks:

  - name: install apache, php and update cache for CentOS and Ubuntu
    package:
      name:
        - "{{ apache }}"
        - "{{ phps }}"
      state: latest
      update_cache: yes

      


